import Head from 'next/head'
import Markdown from '@/components/markdown/Markdown'
import { getWorkPostByPath } from '@/lib/work'

export default function Page() {
  const { content } = getWorkPostByPath('android-app/privacypolicy')
  return (
    <div className="min-h-screen p-5">
      <Head>
        <title>PrivacyPolicy and Support</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-3 ">
        <h1 className="text-xl text-cdorange">PrivacyPolicy and Support</h1>
      </div>
      <article className="p-5 lg:rounded-lg">
        <Markdown source={content} metas={[]} />
      </article>
      <div className="mt-3">
        <h1 className="text-xl text-bold">Support</h1>
        <a
          className="text-blue-400"
          href="https://docs.google.com/forms/d/e/1FAIpQLSc7ZaKERZCEFYUIAlugnYXwuuS8dHoR3ytxDC2TyQOt1FCmqg/viewform?usp=sf_link"
        >
          Contact Me（Google Form）
        </a>
      </div>
    </div>
  )
}
