import React, { useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import DraftjsEditor from '@/components/works/draftjsEditor/DraftjsEditor'
import Markdown from '@/components/markdown/Markdown'

const draftjsEditor: NextPage = () => {
  const [markdownContent, setMarkdownContent] = useState('')

  const onClick = async (markDownStr: string) => {
    if (markDownStr.length < 5) return
    setMarkdownContent(markDownStr)
  }

  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full lg:w-2/3">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdred">draft.js リッチテキストエディタ</h2>
            <div className="my-2 p-5 rounded">
              <DraftjsEditor onClick={onClick} />
            </div>
          </div>
        </div>
        <div>
          <Markdown source={markdownContent} />
        </div>
      </main>
    </div>
  )
}
export default draftjsEditor
