import React from 'react'
import Head from 'next/head'
import BlogPostList from '@/components/BlogPostList'
import { getAllPosts } from '@/lib/blogPosts'

export default function Page() {
  const postsList = getAllPosts(['title', 'date', 'slug', 'author', 'coverImage', 'excerpt'])
  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdorange">Blog Posts</h2>
            <BlogPostList postsList={postsList} />
            {/* <p>{JSON.stringify(postsList)}</p> */}
          </div>
        </div>
      </main>
    </div>
  )
}
