import React from 'react'
import Head from 'next/head'
import { getAllNotes } from '@/lib/note'
import NoteList from '@/components/note/NoteList'

export default function Page() {
  const noteList = getAllNotes()
  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdorange">Note Posts</h2>
            <NoteList noteList={noteList} />
          </div>
        </div>
      </main>
    </div>
  )
}
