import Link from 'next/link'
import Head from 'next/head'
import { ArticleShortList } from '@/components/ArticleShortList'
import { WorkList } from '@/components/works/WorkList'
import { Button } from '@/components/Button'
import { getAllPosts, BlogItem } from '@/lib/blogPosts'
import { sources, FeedItem, getFeedItems } from '@/lib/feedItem'
import BlogPostShortList from '@/components/BlogPostShortList'

export interface HomeInterface {
  feedItems: FeedItem[]
  postsList: any
}

async function fetchFeedItems() {
  return await getFeedItems(sources)
}

function fetchPostsList(): BlogItem[] {
  let postsList = [] as BlogItem[]
  try {
    postsList = getAllPosts(['title', 'date', 'slug', 'author', 'coverImage', 'excerpt'])
  } catch (e) {
    //
  }
  return postsList.slice(0, 10)
}

export default async function Page() {
  const postsList = fetchPostsList()
  const feedItems = await fetchFeedItems()
  const workItems = [
    {
      title: 'ソートアルゴリズム',
      link: 'sort-algorithm',
      isoDate: 'string',
    },
  ]
  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdred">Article</h2>
            <ArticleShortList feedItems={feedItems} />
            <Button label="more Articles" primary={true} />
          </div>
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdorange">Blog Posts</h2>
            <BlogPostShortList postsList={postsList} />
            <Link href="/blog">
              <Button label="more..." primary={true} />
            </Link>
          </div>
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdblue">Works</h2>
            <WorkList workItems={workItems} />
            <Link href="/works">
              <Button label="more..." primary={true} />
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}
