import Head from 'next/head'
import privacyPolicy from './privacyPolicy.json'

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="min-h-screen p-5">
      <Head>
        <title>PrivacyPolicy and Support</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-3 ">
        <h1 className="text-xl text-cdorange">PrivacyPolicy and Support</h1>
      </div>
      {privacyPolicy.items.map((item) => {
        return (
          <div className="mt-5" key={item.title}>
            <h3 className="font-bold">{item.title}</h3>
            {item.description && <p>{item.description}</p>}
            {item.listitems && (
              <ol className="m-2 pl-5 list-decimal">
                {item.listitems.map((listitem) => {
                  return (
                    <li key={listitem.title}>
                      <h5>{listitem.title}</h5>
                    </li>
                  )
                })}
              </ol>
            )}
          </div>
        )
      })}
      <div className="pt-3">
        <p>This policy is effective as of 2021-12-30</p>
        <p>
          This privacy policy page was created at privacypolicytemplate.net and modified/generated
          by App Privacy Policy Generator
        </p>
      </div>
      <div className="mt-3">
        <h1 className="text-xl text-bold">Support</h1>
        <a
          className="text-blue-400"
          href="https://docs.google.com/forms/d/1xLAYBHwluRPkXL9PLBDpR8eumxwNoURBHHDzqQHatrI/viewform?edit_requested=true"
        >
          Contact Me（Google Form）
        </a>
      </div>
    </div>
  )
}
export default PrivacyPolicy
