import React from 'react'
import Head from 'next/head'
import BlogPostList from '@/components/BlogPostList'
import { getAllPosts } from '@/utils/utils'
import { ProfileCard } from '@/components/ProfileCard'

export interface BlogIntexInterface {
  postsList: any
}

const BlogIndex: React.FC<BlogIntexInterface> = ({ postsList }) => {
  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full lg:w-2/3">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdorange">Blog Posts</h2>
            <BlogPostList postsList={postsList} />
            {/* <p>{JSON.stringify(postsList)}</p> */}
          </div>
        </div>
        <div className="w-full lg:w-1/3 pt-12 px-5">
          <ProfileCard />
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const postsList = getAllPosts(['title', 'date', 'slug', 'author', 'coverImage', 'excerpt'])
  return { props: { postsList } }
}

export default BlogIndex
