import Head from 'next/head'
import { ArticleShortList } from '@/components/ArticleShortList'
// import { BlogPostShortList } from '@/components/BlogPostShortList'
import { WorkList } from '@/components/works/WorkList'
import { ProfileCard } from '@/components/ProfileCard'
import { Button } from '@/components/Button'
import { useRouter } from 'next/router'
import { feedItem } from 'types'
import { getFeedItems, getAllPosts } from '@/utils/utils'
import { sources } from '@/utils/sources'
import BlogPostShortList from '@/components/BlogPostShortList'

export interface HomeInterface {
  feedItems: feedItem[]
  postsList: any
}

const Home: React.FC<HomeInterface> = ({ feedItems, postsList }) => {
  const router = useRouter()
  const workItems = [
    {
      title: 'ソートアルゴリズム',
      link: 'sort-algorithm',
      isoDate: 'string',
    },
  ]
  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full lg:w-2/3">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdred">Articles</h2>
            <ArticleShortList feedItems={feedItems} />
            <Button label="more Articles" primary={true} onClick={() => router.push('/articles')} />
          </div>
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdorange">Blog Posts</h2>
            <BlogPostShortList postsList={postsList} />

            <Button label="more..." primary={true} onClick={() => router.push('/blog')} />
          </div>
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdblue">Works</h2>
            <WorkList workItems={workItems} />
            <Button label="more..." primary={true} onClick={() => router.push('/works')} />
          </div>
        </div>
        <div className="w-full lg:w-1/3 pt-12 px-5 py-3">
          <ProfileCard />
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  let feedItems = []
  let postsList = []
  try {
    feedItems = await getFeedItems(sources)
    postsList = await getAllPosts(['title', 'date', 'slug', 'author', 'coverImage', 'excerpt'])
  } finally {
    // eslint-disable-next-line no-unsafe-finally
    return { props: { feedItems: feedItems, postsList: postsList } }
  }
}

export default Home
