import Head from 'next/head'
import { WorkList } from '@/components/works/WorkList'

export default function Page() {
  const workItems = [
    {
      title: 'ソートアルゴリズム',
      link: 'sort-algorithm',
      isoDate: 'string',
    },
    {
      title: 'draft.js エディタ',
      link: 'draftjs-editor',
      isoDate: 'string',
    },
  ]

  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdred">Articles</h2>
            <WorkList workItems={workItems} />
          </div>
        </div>
      </main>
    </div>
  )
}
