import Head from 'next/head'
import { ArticleList } from '@/components/ArticleList'
import { FeedItem, sources, getFeedItems } from '@/lib/feedItem'

export interface ArticlesInterface {
  feedItems: FeedItem[]
}

async function fetchFeedItems() {
  return await getFeedItems(sources)
}

export default async function Page() {
  const feedItems = await fetchFeedItems()
  return (
    <div className="min-h-screen p-2.5">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full">
          <div className="p-3">
            <h2 className="text-xl font-bold text-cdred">Articles</h2>
            <ArticleList feedItems={feedItems} />
          </div>
        </div>
      </main>
    </div>
  )
}
