import Head from 'next/head'
import terms from './terms.json'

export default function Page() {
  return (
    <div className="min-h-screen p-5">
      <Head>
        <title>iOS App Terms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-3">
        <h1 className="text-xl font-bold text-cdorange">iOS App Terms</h1>
        <p className="p-2">{terms.preamble}</p>
        {terms.items.map((item) => {
          return (
            <div className="mt-5" key={item.title}>
              <h3 className="font-bold">{item.title}</h3>
              {item.description && <p>{item.description}</p>}
            </div>
          )
        })}
      </div>
    </div>
  )
}
